my_site/urls.py
from django.contrib import admin
from django.urls import path, include
from p_library import views
from p_library.views import AuthorEdit, AuthorList, author_create_many, books_authors_create_many

urlpatterns = [
    path('p_library/', include('p_library.urls', namespace='p_library')),
    path('admin/', admin.site.urls),
    path('', views.books_list),
    path('index/', views.index),
    path('index/book_increment/', views.book_increment),
    path('index/book_decrement/', views.book_decrement),
    path('editors/', views.editors),
    path('authors', AuthorList.as_view(), name='author_list'),
    path('author/create', AuthorEdit.as_view(), name='author_create'),
    path('author/create_many', author_create_many, name='author_create_many'),
    path('author_book/create_many', author_create_many, name='author_book_create_many'),
    path('friends/', views.FriendList.as_view(), name='friend_list'),
    path('friends/create', views.FriendCreate.as_view(), name='friend_create'),
]
app_name = 'p_library'

from django.conf.urls.static import static
from django.conf import settings

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

p_library/urls.py
from django.urls import path
from p_library import views

app_name = "p_library"

urlpatterns = [
    path('', views.BookList.as_view(), name="book_list"),
    path('create', views.BookCreate.as_view(), name="book_create"),
    path("update<int:pk>", views.BookUpdate.as_view(), name="book_update"),
    path('library/', views.library, name='library'),
    path('library/book_increment/', views.book_increment),
    path('library/book_decrement/', views.book_decrement),
    path('library/borrowed_book/', views.borrowed_book),
    path('library/returned_book/', views.returned_book),
    path('authors/', views.AuthorList.as_view(), name='author_list'),
    path('authors/create', views.AuthorCreate.as_view(), name='author_create'),
    path("authors/update<int:pk>", views.AuthorUpdate.as_view(), name="author_update"),
    path('editor/', views.EditorList.as_view(), name='editor_list'),
    path('editor/create', views.EditorCreate.as_view(), name='editor_create'),
    path("editor/update<int:pk>", views.EditorUpdate.as_view(), name="editor_update"),
    path('friends/', views.FriendList.as_view(), name='friend_list'),
    path('friends/create', views.FriendCreate.as_view(), name='friend_create'),
    path("friends/update<int:pk>", views.FriendUpdate.as_view(), name="friend_update"),
]

p_library/models.py
from django.db import models

# Create your models here.
from django.db import models  

class Author(models.Model):  
    full_name = models.TextField()  
    birth_year = models.SmallIntegerField()  
    country = models.CharField(max_length=2)

    def __str__(self):  
        return "{},{}".format(self.full_name,self.birth_year)

class Editor(models.Model):
    name = models.CharField(max_length=128)

    def __str__(self):
        return self.name

class Friend(models.Model):
    full_name = models.TextField()
    
    def __str__(self):
        return self.full_name

class Book(models.Model):  
    ISBN = models.CharField(max_length=13)  
    title = models.TextField()  
    description = models.TextField()  
    year_release = models.SmallIntegerField()  
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    copy_count = models.SmallIntegerField()
    price = models.DecimalField(max_digits=15, decimal_places=2)
    editor = models.ForeignKey('Editor', on_delete=models.CASCADE,null=True,blank=True,related_name='books')
    friend = models.ManyToManyField('Friend',blank=True,related_name='friends')
    borrowed_book_count = models.SmallIntegerField(default=0)
    cover = models.ImageField(verbose_name='Обложка',upload_to='covers',blank=True)

    def __str__(self):
        return self.title

p_library/forms.py
from django import forms  
from p_library.models import Author, Book, Editor, Friend
from django.forms.widgets import ClearableFileInput

class MyClearableFileInput(ClearableFileInput):
    initial_text = 'Текущяя'
    input_text = 'Изменить'
    clear_checkbox_label = 'Удалить'

class AuthorForm(forms.ModelForm):  
    full_name = forms.CharField(
        label='Имя автора',
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'form-control',
                'placeholder': 'Введите имя автора'
            }
        )
    )
    birth_year = forms.CharField(
        label='Дата рождения автора',
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'form-control',
                'placeholder': 'Введите дату рождения автора'
            }
        )
    )
    country = forms.CharField(
        label='Страна происхождения',
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'form-control',
                'placeholder': 'Введите страну'
            }
        )
    )
    class Meta:
        model = Author
        fields = '__all__'

class BookForm(forms.ModelForm):  
    ISBN = forms.CharField(
        label='ISBN',
        widget=forms.TextInput(
            attrs={
                'required': True,
                'type':'number',
                'class': 'form-control',
                'placeholder': 'Введите ISBN = 13 чисел'
            }
        )
    )
    title = forms.CharField(
        label='Название книги',
        widget=forms.TextInput(
            attrs={
                'required': True,
                'type': 'text',
                'class': 'form-control',
                'placeholder': 'Введите название книги'
            }
        )
    )
    description = forms.CharField(
        label='Описание книги',
        widget=forms.Textarea(
            attrs={
                'required': True,
                'class': 'form-control',
                'rows': '3',
                'placeholder': 'Введите описание книги'
            }
        )
    )
    year_release = forms.CharField(
        label='Дата публикации',
        widget=forms.TextInput(
            attrs={
                'required': True,
                'type': 'number',
                'class': 'form-control',
                'placeholder': 'Введите дату создания книги'
            }
        )
    )
    author = forms.ModelChoiceField(
        queryset=Author.objects.all(),
        label='Автор книги',
        widget=forms.Select(
            attrs={
                'required': True,
                'class': 'form-control'
            }
        )
    )
    editor = forms.ModelChoiceField(
        queryset=Editor.objects.all(),
        label='Издательство',
        widget=forms.Select(
            attrs={
                'required': True,
                'class': 'form-control'
            }
        )
    )
    copy_count = forms.CharField(
        label= 'Общее количество книг',
        widget= forms.TextInput(
            attrs={
                'required': True,
                'type': 'number',
                'class': 'form-control',
                'placeholder': 'Введите общее количество книг'
            }
        )
    )
    price = forms.CharField(
        label= 'Цена книги',
        widget= forms.TextInput(
            attrs={
                'required': True,
                'type': 'number',
                'class': 'form-control',
                'placeholder': 'Введите стоимость книги'
            }
        )
    )
    cover = forms.ImageField(
        label= 'Обложка',
        required=False,
        widget= MyClearableFileInput(
            attrs={
                'class': 'form-control',
                'accept': '.jpg,.jpeg,.png,.gif'
            }
        )
    )
    class Meta:
        model = Book
        fields = ('ISBN', 'title', 'description', 'year_release', 'author', 'price', 'copy_count', 'editor', 'cover')

class FriendForm(forms.ModelForm):  
    full_name = forms.CharField(
        label='Имя друга',
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'form-control',
                'placeholder': 'Введите имя друга'
            }
        )
    )
    class Meta:
        model = Friend
        fields = '__all__'

class EditorForm(forms.ModelForm):
    name = forms.CharField(
        label='Издательство',
        widget=forms.TextInput(
            attrs={
                'type': 'text',
                'class': 'form-control',
                'placeholder': 'Введите название издательства'
            }
        )
    )
    class Meta:
        model = Editor
        fields = '__all__'

p_library/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.template import loader
from p_library.models import Author, Book, Editor, Friend
from p_library.forms import AuthorForm, BookForm, EditorForm, FriendForm
from django.views.generic import CreateView, ListView, UpdateView
from django.urls import reverse_lazy
from django.forms import formset_factory  
from django.http.response import HttpResponseRedirect

# Create your views here.
#def books_list(request):
#    books = Book.objects.all()
#    return HttpResponse(books)

class BookList(ListView):
    model = Book
    template_name = 'book_list.html'

class BookUpdate(UpdateView):
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('p_library:book_list')
    template_name = 'book_edit.html'

class BookCreate(CreateView):
    model = Book
    form_class = BookForm
    success_url = reverse_lazy('p_library:book_list')
    template_name = 'book_edit.html'

class AuthorUpdate(UpdateView):
    model = Author
    form_class = AuthorForm
    success_url = reverse_lazy('p_library:author_list')
    template_name = 'author_edit.html'

class AuthorCreate(CreateView):
    model = Author
    form_class = AuthorForm
    success_url = reverse_lazy('p_library:author_list')
    template_name = 'author_edit.html'

class AuthorList(ListView):  
    model = Author  
    template_name = 'author_list.html'

class FriendCreate(CreateView):
    model = Friend
    form_class = FriendForm
    success_url = reverse_lazy('p_library:friend_list')
    template_name = 'friend_edit.html'

class FriendList(ListView):
    model = Friend
    template_name = 'friend_list.html'

class FriendUpdate(UpdateView):
    model = Friend
    form_class = FriendForm
    success_url = reverse_lazy('p_library:friend_list')
    template_name = 'friend_edit.html'

class EditorUpdate(UpdateView):
    model = Editor
    form_class = EditorForm
    success_url = reverse_lazy('p_library:editor_list')
    template_name = 'editor_edit.html'

class EditorCreate(CreateView):
    model = Editor
    form_class = EditorForm
    success_url = reverse_lazy('p_library:editor_list')
    template_name = 'editor_edit.html'

class EditorList(ListView):
    model = Editor
    template_name = 'editor_list.html'

def library(request):
    template = loader.get_template('library.html')
    books = Book.objects.all()
    friends = Friend.objects.all()
    biblio_data = {
        "title": "мою библиотеку",
        "books": books,
        "friends": friends,
    }
    return HttpResponse(template.render(biblio_data, request))

def book_increment(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('/library/')
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect('/library/')
            book.copy_count += 1
            book.save()
        return redirect('/library/')
    else:
        return redirect('/library/')

def book_decrement(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        if not book_id:
            return redirect('/library/')
        else:
            book = Book.objects.filter(id=book_id).first()
            if not book:
                return redirect('/library/')
            if book.copy_count < 1:
                book.copy_count = 0
            else:
                book.copy_count -= 1
            book.save()
        return redirect('/library/')
    else:
        return redirect('/library/')

def borrowed_book(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        friend_id = request.POST['select_borrowed']
        if not book_id:
            return redirect('/library/')
        else:
            book = Book.objects.filter(id=book_id).first()
            friend = Friend.objects.get(id=friend_id)
            if not book:
                return redirect('/library/')
            if book.copy_count < 1:
                book.copy_count = 0
            else:
                book.copy_count -= 1
                book.borrowed_book_count += 1
                book.friend.add(friend)
            book.save()
        return redirect('/library/')
    else:
        return redirect('/library/')

def returned_book(request):
    if request.method == 'POST':
        book_id = request.POST['id']
        friend_id = request.POST['select_returned']
        if not book_id:
            return redirect('/library/')
        else:
            book = Book.objects.filter(id=book_id).first()
            friend = Friend.objects.get(id=friend_id)
            if not book:
                return redirect('/library/')
            if book.borrowed_book_count < 1:
                book.borrowed_book_count = 0
            else:
                book.copy_count += 1
                book.borrowed_book_count -= 1
                book.friend.remove(friend)
            book.save()
        return redirect('/library/')
    else:
        return redirect('/library/')

p_library/templates/author_edit.html
{% extends 'base.html' %}

{% block title %}Форма создания и редактирования авторов{% endblock %}

{% block title_h2 %}Форма создания и редактирования авторов:{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-success my-3" type="submit" value="Сохранить">
        <a class="btn btn-danger my-3" href="{%url 'p_library:author_list'%}">Отмена</a>
    </form>
{% endblock %}

p_library/templates/author_list.html
{% extends 'base.html' %}

{% block title %}Список авторов{% endblock %}

{% block link %}

    <div class="text-secondary text-center font-weight-bold my-3">
        <a class="text-secondary text-decoration-none" href="{%url 'p_library:book_list'%}">Книги</a> | 
        <a class="text-secondary text-decoration-none" href="{%url 'p_library:library'%}">Библиотека</a> | 
        <a class="text-secondary text-decoration-none" href="{%url 'p_library:editor_list'%}">Издательства</a> | 
        <a class="text-secondary text-decoration-none" href="{%url 'p_library:friend_list'%}">Друзья</a>
    </div>

{% endblock %}

{% block title_h2 %}Список авторов книг:{% endblock %}

{% block content %}

    <table class="table table-dark table-stripped table-hover">
        {% for author in object_list %}
        <tr class="table-bordered">
            <td style="width:20px;">{{ forloop.counter }}</td>
            <td>{{ author.full_name }}</td>
            <td style="width:20px;text-align:right;"><a class="btn btn-warning" href="{%url 'p_library:author_update' author.id %}">Изменить</a></td>
        </tr>
        {% endfor %}
    </table>
    <a class="btn btn-success my-3" href="{%url 'p_library:author_create'%}">Добавить автора</a>

{% endblock %}

p_library/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <div class="container-fluid">
        <div class="row">
            <div class="col-12 my-3">
                {% block link %}{% endblock %}
    			<h2 class="text-secondary text-center my-3">{% block title_h2 %}{% endblock %}</h2>
                {% block content %}{% endblock %}
            </div>
        </div>  
    </div>
</body>
</html>

p_library/templates/book_edit.html
{% extends 'base.html' %}

{% block title %}Форма создания и редактирования книг{% endblock %}

{% block title_h2 %}Форма создания и редактирования книг:{% endblock %}

{% block content %}
    <form enctype="multipart/form-data" method="post"> 
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-success my-3" type="submit" value="Сохранить">
        <a class="btn btn-danger my-3" href="{%url 'p_library:book_list'%}">Отмена</a>
    </form>
{% endblock %}

p_library/templates/book_list.html
{% extends 'base.html' %}

{% block title %}Мои книги{% endblock %}

{% block link %}

    <div class="text-secondary text-center font-weight-bold my-3">
        <a class="text-secondary text-decoration-none" href="{%url 'p_library:library'%}">Библиотека</a> | 
        <a class="text-secondary text-decoration-none" href="{%url 'p_library:author_list'%}">Авторы</a> | 
        <a class="text-secondary text-decoration-none" href="{%url 'p_library:editor_list'%}">Издательства</a> | 
        <a class="text-secondary text-decoration-none" href="{%url 'p_library:friend_list'%}">Друзья</a>
    </div>

    <div class="container my-4">
        <a class="btn btn-success" href="{%url 'p_library:book_create'%}">Добавить книгу в библиотеку</a>
    </div>

{% endblock %}

{% block title_h2 %}Список книг:{% endblock %}

{% block content %}

    <ul class="container list-group list-group-flush">
        {% for book in object_list %}
        <div class="row mt-3">
            <div class="col">
                <ul class="list-group text-secondary">
                    <h1 class="h3 font-weight-bold mt-5">{{book.title}}</h1>
                    <li class="d-flex justify-content-between list-group-item">
                        <div class="h5 font-italic">{{book.author}}</div>
                        <div class="h5 font-bold">{{book.year_release}}</div>
                    </li>
                    <li class="d-flex list-group-item">
                        <p class="h5 font-weight-light">{{book.description|truncatechars:200}}</p>
                    </li>
                    <div class="col text-right mx-5 my-3">
                        <a class="btn btn-warning" href="{%url 'p_library:book_update' book.id %}">Изменить</a>
                    </div>
                        
                </ul>
            </div>
            {%if book.cover%}
            <div class="col text-right">
                <img src="{{ book.cover.url }}" alt="" width="200">
            </div>              
            {% endif %}    
        </div>  
        {% endfor %}
    </ul>
    <div class="container my-3">
        <a class="btn btn-success" href="{%url 'p_library:book_create'%}">Добавить книгу в библиотеку</a>
    </div>

{% endblock %}

p_library/templates/editor_edit.html
{% extends 'base.html' %}

{% block title %}Форма создания и редактирования издательств{% endblock %}

{% block title_h2 %}Форма создания и редактирования издательств:{% endblock %}

{% block content %}
    <form method="post"> 
        {% csrf_token %}
        {{ form.as_p }}
        <input class="btn btn-success my-3" type="submit" value="Сохранить">
        <a class="btn btn-danger my-3" href="{%url 'p_library:editor_list'%}">Отмена</a>
    </form>
{% endblock %}

p_library/templates/editor_list.html
{% extends 'base.html' %}

{% block title %}Издательства{% endblock %}

{% block link %}

	<div class="text-secondary text-center font-weight-bold my-3">
	    <a class="text-secondary text-decoration-none" href="{%url 'p_library:book_list'%}">Книги</a> | 
	    <a class="text-secondary text-decoration-none" href="{%url 'p_library:library'%}">Библиотека</a> | 
	    <a class="text-secondary text-decoration-none" href="{%url 'p_library:author_list'%}">Авторы</a> | 
	    <a class="text-secondary text-decoration-none" href="{%url 'p_library:friend_list'%}">Друзья</a>
	</div>

{% endblock %}

{% block title_h2 %}Список издательств:{% endblock %}

{% block content %}

    {% for publisher in object_list %}
        <ul class="list-group font-weight-bold">
            <li class="list-group-item list-group-item-dark my-3">
                {{ publisher.name }}
                <ul class="list-group">
                    {% for book in publisher.books.all %}
                        <li class="list-group-item list-group-item-secondary"> {{ book.title }}</li>
                    {% endfor %}
                </ul>
                <div style="margin-top:10px;text-align:right;"><a class="btn btn-warning" href="{%url 'p_library:editor_update' editor.id %}">Изменить</a></div>
            </li>
        </ul>
    {% endfor %}
    <a class="btn btn-success my-3" href="{%url 'p_library:editor_create'%}">Добавить издательство</a>

{% endblock %}

p_library/templates/friend_edit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Форма создания и редактирования друзей</title>
</head>
<body>
    <div class="container">
        <div class="col-12 my-3">
            <h2 class="text-center my-3">Форма создания и редактирования друзей:</h2>
            <form method="post"> 
                {% csrf_token %}
                {{ form.as_p }}
                <input class="btn btn-success my-3" type="submit" value="Сохранить">
                <a class="btn btn-danger my-3" href="{%url 'p_library:friend_list'%}">Отмена</a>
            </form>
        </div>  
    </div>
</body>
</html>

p_library/templates/friend_list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>Список друзей</title>
</head>
<body>
    <div class="container">
        <div class="row">
            <div class="col-12 my-3">
                <h2 class="text-secondary text-center my-3">Список друзей:</h2>
                <table class="table table-dark table-stripped table-hover">
                    {% for friend in object_list %}
                    <tr class="table-bordered">
                        <td style="width:20px;">{{ forloop.counter }}</td>
                        <td>{{ friend.full_name }}</td>
                    </tr>
                    {% endfor %}
                </table>
                <a class="btn btn-success my-3" href="{%url 'p_library:friend_create'%}">Добавить друга</a>
            </div>
        </div>
    </div>
</body>
</html>

p_library/templates/library.html
{% extends 'base.html' %}

{% block title %}Моя библиотека{% endblock %}

{% block link %}

    <div class="text-secondary text-center font-weight-bold my-3">
        <a class="text-secondary text-decoration-none" href="{%url 'p_library:book_list'%}">Книги</a> | 
        <a class="text-secondary text-decoration-none" href="{%url 'p_library:author_list'%}">Авторы</a> | 
        <a class="text-secondary text-decoration-none" href="{%url 'p_library:editor_list'%}">Издательства</a> | 
        <a class="text-secondary text-decoration-none" href="{%url 'p_library:friend_list'%}">Друзья</a>
    </div>

{% endblock %}

{% block content %}

    <h3 class="text-secondary text-center my-3">Добро пожаловать в {{ title }}.</h3>
    <h5 class="text-secondary text-center my-3">Тут собрано {{ books|length }} книг из моей личной коллекции.</h5>
    <table class="table table-dark table-stripped table-hover">
        <thead class="thead-light">
            <tr class="table-bordered text-center">
                <th>№</th>
                <th>Название книги</th>
                <th>Обложка</th>
                <th>ISBN</th>
                <th>О книге</th>
                <th>Год</th>
                <th>Автор</th>
                <th>Издательство</th>
                <th>Страна</th>
                <th>Кол-во книг в библиотеке</th>
                <th>Кол-во одолженных книг и кто одолжил</th>
                <th>Изменить кол-во книг в библиотеке</th>
                <th>Одолжить или вернуть книги</th>
            </tr>
        </thead>
        <tbody class="table-bordered text-center">
            {% for book in books %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>{{ book.title }}</td>
                <td>
                    {% if book.cover %}
                    <img src="{{ book.cover.url }}" width="100" alt="">
                    {% endif %}
                </td>
                <td>{{ book.ISBN }}</td>
                <td>{{ book.description }}</td>
                <td>{{ book.year_release }}</td>
                <td>{{ book.author.full_name }}</td>
                <td>{{ book.editor }}</td>
                <td>{{ book.author.country }}</td>
                <td>{{ book.copy_count }}</td>
                <td>
                    <p>{{ book.borrowed_book_count }}</p>
                    {% for friend in friends.all %}
                    {% if friend in book.friend.all %}
                    <p class="my-1 px-1 py-1 bg-secondary text-white rounded">{{ friend.full_name }}</p>
                    {% endif %}
                    {% endfor %}
                </td>
                <td>
                    <form class="my-2" action="/library/book_increment/" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{ book.id }}" />
                        <input class="btn btn-warning btn-sm" type="submit" value="Увеличить кол-во" />
                    </form>
                    <form class="my-2" action="/library/book_decrement/" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <input type="hidden" name="id" value="{{ book.id }}" />
                        <input class="btn btn-success btn-sm" type="submit" value="Уменьшить кол-во" />
                    </form>
                </td>
                <td>
                    {% if book.copy_count and book.friend.all|length != friends.all|length %}
                    <form class="form-row" action="/library/borrowed_book/" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <select style="width:20vw;" class="col custom-select my-1 mr-sm-2" name="select_borrowed" size="1">
                            {% for friend in friends.all %}
                            {% if friend not in book.friend.all %}
                            <option value="{{ friend.id }}">{{ friend.full_name }}</option>
                            {% endif %}
                            {% endfor %}
                        </select>
                        <input type="hidden" name="id" value="{{ book.id }}" />
                        <input class="col btn btn-warning my-1" type="submit" value="Одолжить" />
                    </form>
                    {% endif %}
                    {% if book.friend.all %}
                    <form class="form-row" action="/library/returned_book/" method="post" enctype="multipart/form-data">
                        {% csrf_token %}
                        <select style="width:20vw;" class="col custom-select my-1 mr-sm-2" name="select_returned" size="1">
                            {% for friend in book.friend.all %}
                            <option value="{{ friend.id }}">{{ friend.full_name }}</option>
                            {% endfor %}
                        </select>
                        <input type="hidden" name="id" value="{{ book.id }}" />
                        <input class="col btn btn-success my-1" type="submit" value="Вернуть" />
                    </form>
                    {% endif %}
                </td>
            </tr>
            {% endfor %}
        <tbody>
    </table>
 
{% endblock %}

p_library/templates/manage_authors.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
 <meta charset="UTF-8">  
 <title>Create multiple authors</title>  
</head>  
<body>  
<form method="post">  
	{% csrf_token %}  
	{% for form in author_formset %}  
		{{ form.as_ul }}  
		<br>  
	{% endfor %}
    <input type="submit" value="Сохранить"/>  
</form>  
</body>  
</html>

p_library/templates/manage_books_authors.html
<!DOCTYPE html>  
<html lang="en">  
<head>  
 <meta charset="UTF-8">  
 <title>Create multiple Authors and Books</title>  
</head>  
<body>  
<form method="post">  
  {% csrf_token %}  
  {% for form in author_formset %}  
        {{ form.as_ul }}  
        <br>  
  {% endfor %}  
  
    {% for form in book_formset %}  
        {{ form.as_ul }}  
        <br>  
  {% endfor %}  
    <input type="submit" value="Сохранить"/>  
</form>  
</body>  
</html>